# @remove-file-mobile
on:
  pull_request:
    paths:
      - packages/common/**
      - packages/mobile/**
jobs:
  test:
    name: Node.js CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn --cwd packages/common build
      - run: yarn --cwd packages/mobile test
        env:
          CI: true
